[package]
name = "mmv"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.16"
clap = { version = "4.5.20", features = ["derive"] }
fnmatch-regex = "0.2.1"
regex = "1.11.0"
regex-syntax = "0.8.5"
tempdir = "0.3.7"
walkdir = "2.5.0"
